// Initial demo data. Everything downstream (balances, inventory, sales
// totals) is derived from this single set of transactions so numbers never
// disagree between pages.

export const INITIAL_MEMBERS = [
  { id: 'TW001', name: 'ณัฐวุฒิ ใจดี', phone: '081-234-5671' },
  { id: 'TW002', name: 'พิมพ์ชนก แสงทอง', phone: '081-234-5672' },
  { id: 'TW003', name: 'ธีรภัทร ศรีสุข', phone: '081-234-5673' },
  { id: 'TW004', name: 'กมลชนก บุญมี', phone: '081-234-5674' },
  { id: 'TW005', name: 'สุพิชญา รักเรียน', phone: '081-234-5675' },
  { id: 'TW006', name: 'อดิศักดิ์ ทองแท้', phone: '081-234-5676' },
];

const day = (offset) => {
  const d = new Date();
  d.setDate(d.getDate() - offset);
  return d.toISOString();
};

// Transaction types: 'purchase' | 'sale' | 'withdrawal'
export const INITIAL_TRANSACTIONS = [
  // Opening stock, not tied to any member.
  {
    id: 'TX0001',
    type: 'purchase',
    date: day(20),
    memberId: null,
    isOpeningStock: true,
    wasteTypeId: 'plastic',
    description: 'สต๊อกเริ่มต้นระบบ',
    quantity: 25,
    unit: 'kg',
    pricePerUnit: 10,
    amount: 250,
    credit: 0,
    debit: 0,
    balanceAfter: null,
    reference: 'OPEN-001',
  },
  {
    id: 'TX0002',
    type: 'purchase',
    date: day(20),
    memberId: null,
    isOpeningStock: true,
    wasteTypeId: 'paper',
    description: 'สต๊อกเริ่มต้นระบบ',
    quantity: 18,
    unit: 'kg',
    pricePerUnit: 8,
    amount: 144,
    credit: 0,
    debit: 0,
    balanceAfter: null,
    reference: 'OPEN-001',
  },
  // Member purchases
  {
    id: 'TX0003',
    type: 'purchase',
    date: day(14),
    memberId: 'TW001',
    wasteTypeId: 'plastic',
    description: 'รับซื้อขวดพลาสติก',
    quantity: 5,
    unit: 'kg',
    pricePerUnit: 10,
    amount: 50,
    credit: 50,
    debit: 0,
    balanceAfter: 50,
    reference: 'PUR-001',
  },
  {
    id: 'TX0004',
    type: 'purchase',
    date: day(14),
    memberId: 'TW001',
    wasteTypeId: 'can',
    description: 'รับซื้อกระป๋อง',
    quantity: 3,
    unit: 'kg',
    pricePerUnit: 15,
    amount: 45,
    credit: 45,
    debit: 0,
    balanceAfter: 95,
    reference: 'PUR-001',
  },
  {
    id: 'TX0005',
    type: 'purchase',
    date: day(12),
    memberId: 'TW002',
    wasteTypeId: 'paper',
    description: 'รับซื้อกระดาษ',
    quantity: 10,
    unit: 'kg',
    pricePerUnit: 8,
    amount: 80,
    credit: 80,
    debit: 0,
    balanceAfter: 80,
    reference: 'PUR-002',
  },
  {
    id: 'TX0006',
    type: 'purchase',
    date: day(10),
    memberId: 'TW003',
    wasteTypeId: 'glass',
    description: 'รับซื้อขวดแก้ว',
    quantity: 12,
    unit: 'kg',
    pricePerUnit: 3,
    amount: 36,
    credit: 36,
    debit: 0,
    balanceAfter: 36,
    reference: 'PUR-003',
  },
  {
    id: 'TX0007',
    type: 'purchase',
    date: day(9),
    memberId: 'TW004',
    wasteTypeId: 'metal',
    description: 'รับซื้อโลหะ',
    quantity: 4,
    unit: 'kg',
    pricePerUnit: 20,
    amount: 80,
    credit: 80,
    debit: 0,
    balanceAfter: 80,
    reference: 'PUR-004',
  },
  {
    id: 'TX0008',
    type: 'purchase',
    date: day(7),
    memberId: 'TW002',
    wasteTypeId: 'plastic',
    description: 'รับซื้อขวดพลาสติก',
    quantity: 6,
    unit: 'kg',
    pricePerUnit: 10,
    amount: 60,
    credit: 60,
    debit: 0,
    balanceAfter: 140,
    reference: 'PUR-005',
  },
  {
    id: 'TX0009',
    type: 'purchase',
    date: day(5),
    memberId: 'TW005',
    wasteTypeId: 'can',
    description: 'รับซื้อกระป๋อง',
    quantity: 7,
    unit: 'kg',
    pricePerUnit: 15,
    amount: 105,
    credit: 105,
    debit: 0,
    balanceAfter: 105,
    reference: 'PUR-006',
  },
  // Sale to buyer (does not touch member balance)
  {
    id: 'TX0010',
    type: 'sale',
    date: day(6),
    memberId: null,
    wasteTypeId: 'plastic',
    description: 'ขายขวดพลาสติกให้ร้านรับซื้อ A',
    buyer: 'ร้านรับซื้อ A',
    quantity: 15,
    unit: 'kg',
    pricePerUnit: 12,
    amount: 180,
    credit: 0,
    debit: 0,
    balanceAfter: null,
    reference: 'SALE-001',
  },
  {
    id: 'TX0011',
    type: 'sale',
    date: day(3),
    memberId: null,
    wasteTypeId: 'paper',
    description: 'ขายกระดาษให้บริษัทรีไซเคิล C',
    buyer: 'บริษัทรีไซเคิล C',
    quantity: 8,
    unit: 'kg',
    pricePerUnit: 10,
    amount: 80,
    credit: 0,
    debit: 0,
    balanceAfter: null,
    reference: 'SALE-002',
  },
  // Withdrawal
  {
    id: 'TX0012',
    type: 'withdrawal',
    date: day(2),
    memberId: 'TW001',
    wasteTypeId: null,
    description: 'ถอนเงินสด',
    quantity: null,
    unit: null,
    pricePerUnit: null,
    amount: 40,
    credit: 0,
    debit: 40,
    balanceAfter: 55,
    reference: 'WD-001',
  },
];

export const INITIAL_EXPENSES = [
  {
    id: 'EX0001',
    date: day(15),
    category: 'วัสดุและอุปกรณ์',
    description: 'ซื้อถุงมือและถุงบรรจุขยะ',
    amount: 320,
  },
  {
    id: 'EX0002',
    date: day(8),
    category: 'ค่าเดินทาง',
    description: 'ค่าน้ำมันรถขนขยะไปจุดรับซื้อ',
    amount: 200,
  },
  {
    id: 'EX0003',
    date: day(4),
    category: 'ค่าดำเนินงาน',
    description: 'ค่าจ้างช่วยขนย้ายขยะ',
    amount: 150,
  },
];
